### ISSUE TITLE
Quantium task 2- get NH for nCustomers 

### ISSUE THREAD

**Issue by tiffanysn** [tiffanysn/general_learning#23]
- [x] Scale pre-trial control customers to match pre-trial trial store customers
- [x]  apply the scaling factor to control store customer counts
- [x] calculate the percentage difference between scaled control store customers and trial customers
- [x] standard deviation
- [x] Control store 5th & 95th percentile
- [x] plot

**Comment by tiffanysn** [comment]
- [ ]  Scale pre-trial control customers to match pre-trial trial store customers

- [ ]  apply the scaling factor to control store customer counts

- [ ] calculate the percentage difference between scaled control store customers and trial customers

- [ ] standard deviation

- [ ] Control store 5th & 95th percentile

- [ ] plot

**Comment by couyang24** [comment]
can you copy the objectives and paste it into the first comment so that it would show in the list level?
